FROM php:8.3.20-apache

# Install dependencies for PDO and MySQL support
RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo pdo_mysql gd
    
COPY ./ /var/www/html
